---
- name: NDFC Connectivity Test
  hosts: ndfc_cisg_lab
  connection: ansible.netcommon.httpapi
  gather_facts: true

  tasks:
  - name: GET info from NDFC
    cisco.dcnm.dcnm_rest:
      method: GET
      path: /rest/control/fabrics
